url=https://akamai-s1-astra-stage.arcelik.com.tr/

url2=https://akamai-s1-astra-stage.arcelik.com.tr/
browser=chrome
sifre=Albayrak.41
kullanici1=beko.s1te.st@gmail.com
#kullanici1=beko.s1test@gmail.com
kullanici2=beko.s1te.st@gmail.com
#kullanici1=bekos1.test@gmail.com
#kullanici2=bekos1.test@gmail.com
kullaniciCanli=bekos1.test@gmail.com
urlCanli=https://www.beko.com.tr/
urunKodu=8914111200